#ifndef HEADERS_H_INCLUDED
#define HEADERS_H_INCLUDED

#define     PI              3.14159265
#define     ANG_RAD         PI/180.0
#define     MAX_FASES       64
#define     MAX_TEXTO       512

enum marcas{JOGO_NADA=0, JOGO_JOGADOR, JOGO_SOLIDO, JOGO_FIM, JOGO_MORTE,
    JOGO_TRIGGER_0, JOGO_TRIGGER_1, JOGO_TRIGGER_2, JOGO_TRIGGER_3, JOGO_TRIGGER_4};


#endif // HEADERS_H_INCLUDED
